apps/article/models.py
from datetime import datetime

from exts import db


class Article(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  title = db.Column(db.String(50), nullable=False)
  content = db.Column(db.Text, nullable=False)
  pdatetime = db.Column(db.DateTime, default=datetime.now)
  click_num = db.Column(db.Integer, default=0)
  save_num = db.Column(db.Integer, default=0)
  love_num = db.Column(db.Integer, default=0)
  #  外键 同步到数据库的外键关系
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
  type_id = db.Column(db.Integer, db.ForeignKey('article_type.id'), nullable=False)
  comments = db.relationship('Comment', backref='article')

  def __str__(self):
    return self.title


class Comment(db.Model):
  #  自定义表名
  __tablename__ = 'comment'
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  comment = db.Column(db.String(300), nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
  article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
  cdatetime = db.Column(db.DateTime, default=datetime.now)

  def __str__(self):
    return self.comment


class Article_type(db.Model):

  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  type_name = db.Column(db.String(20), nullable=False)
  articles = db.relationship('Article', backref='article_type')

apps/goods/models.py
from exts import db


class Goods(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  gname = db.Column(db.String(100), nullable=False)
  price = db.Column(db.Float, nullable=False)
  users = db.relationship('User', backref='goods', secondary='user_goods')

  def __str__(self):
    return self.gname


class User_goods(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
  goods_id = db.Column(db.Integer, db.ForeignKey('goods.id'))
  number = db.Column(db.Integer, default=1)

apps/user/models.py
from datetime import datetime

from exts import db


class User(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  username = db.Column(db.String(15), nullable=False)
  password = db.Column(db.String(200), nullable=False)
  phone = db.Column(db.String(11), unique=True, nullable=False)
  email = db.Column(db.String(30))
  icon = db.Column(db.String(100))
  isdelete = db.Column(db.Boolean, default=False)
  rdatatime = db.Column(db.DateTime, default=datetime.now)
  articles = db.relationship('Article', backref='user')
  comments = db.relationship('Comment', backref='user')

  def __str__(self):
    return self.username


class Photo(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  photo_name = db.Column(db.String(100), nullable=False)
  photo_datetime = db.Column(db.DateTime, default=datetime.now)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

  def __str__(self):
    return self.photo_name


class AboutMe(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  content = db.Column(db.BLOB, nullable=False)
  pdatetime = db.Column(db.DateTime, default=datetime.now)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True)
  user = db.relationship('User', backref='aboutme')


class MessageBoard(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  content = db.Column(db.String(255), nullable=False)
  mdatetime = db.Column(db.DateTime, default=datetime.now)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
  user = db.relationship('User', backref='messages')

app.py
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from apps import create_app
from exts import db

from apps.user.models import *
from apps.article.models import *
from apps.goods.models import *

app = create_app()
manager = Manager(app=app)

migrate = Migrate(app=app, db=db)

manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
  manager.run()

apps/__init__.py
from flask import Flask

import settings

from apps.article.views import article_bp1
from apps.user.view import user_bp
from exts import db, bootstrap


def create_app():
  app = Flask(__name__, template_folder='../templates', static_folder='../static')
  app.config.from_object(settings.DevelopmentConfig)
  # 初始化配置db
  db.init_app(app=app)

  bootstrap.init_app(app=app)

  app.register_blueprint(user_bp)
  app.register_blueprint(article_bp1)

  return app

apps/article/views.py
from flask import Blueprint, request, g, redirect, url_for, render_template, jsonify, session

from apps.article.models import Article, Article_type, Comment
from apps.user.models import User
from exts import db

article_bp1 = Blueprint('article', __name__, url_prefix='/article')


@article_bp1.route('/publish', methods=['GET', 'POST'])
def article_publish():
  if request.method == 'POST':
    title = request.form.get('title')
    type_id = request.form.get('type')
    content = request.form.get('content')
    article = Article()
    article.title = title
    article.type_id = type_id
    article.content = content
    article.user_id = g.user.id
    db.session.add(article)
    db.session.commit()
    return redirect(url_for('user.index'))
  return redirect(url_for('user.user_center'))


@article_bp1.route('/detail')
def article_detail():
  article_id = request.args.get('aid')
  article = Article.query.get(article_id)
  types = Article_type.query.all()
  user_id = session.get('uid')
  user = None
  if user_id:
    user = User.query.get(user_id)
  page = int(request.args.get('page', 1))
  comments = Comment.query.filter(Comment.article_id == article_id).paginate(page=page, per_page=5)
  return render_template('article/detail.html', article=article, types=types, user=user, comments=comments)


@article_bp1.route('love')
def article_love():
  article_id = request.args.get('aid')
  tag = request.args.get('tag')
  article = Article.query.get(article_id)
  if tag == '1':
    article.love_num -= 1
  else:
    article.love_num += 1
  db.session.commit()
  return jsonify(love=article.love_num)


@article_bp1.route('/add_comment', methods=['GET', "POST"])
def add_comment():
  if request.method == 'POST':
    comment = request.form.get('comment')
    user_id = g.user.id
    article_id = request.form.get('aid')
    comment1 = Comment()
    comment1.comment = comment
    comment1.user_id = user_id
    comment1.article_id = article_id
    db.session.add(comment1)
    db.session.commit()
    return redirect(url_for('article.article_detail') + "?aid=" + article_id)
  return redirect(url_for('user.index'))

exts/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import  Bootstrap

db = SQLAlchemy()
bootstrap = Bootstrap()

templates/article/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加文章</title>
</head>
<body>
<form action="{{ url_for('article.publish_article') }}" method="post">
    <p><input type="text" name="title" placeholder="文章标题"></p>
    <p>
        <textarea cols="50" rows="10" placeholder="输入文章内容" name="content">

        </textarea>
    </p>
    <p>
        用户：
        <select name="uid">
            <option value="0">请选择用户</option>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </p>
    <p><input type="submit" value="发布文章"></p>
</form>
</body>
</html>

templates/article/all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #container{
            border: 1px solid brown;
            margin-bottom: 10px;
            padding: 5px;
        }
    </style>
</head>
<body>
{% for article in articles %}
<div id="container">
    <p>
        <h3>{{ article.title }}</h3>
        <div>作者：{{ article.user.username }}--{{ article.pdatetime }}</div>
    </p>
    <p>
        {{ article.content }}
    </p>
</div>
{% endfor %}


</body>
</html>

templates/article/all1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for article in user.articles %}
<div id="container">
    <p>
        <h3>{{ article.title }}</h3>
        <div>作者：{{ article.user.username }}--{{ article.pdatetime }}</div>
    </p>
    <p>
        {{ article.content }}
    </p>
</div>
{% endfor %}
</body>
</html>

templates/article/detail.html
{% extends 'base.html' %}

{% block title %}
    文章详情
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1000px;
            margin: 0 auto;
            background-color: rgba(30, 150, 196, 0.5);
        }

        #left {
            float: left;
        }

        #right {
            float: right;
        }
        #item{
            background-color: rgba(255, 255, 255, 0.5);
            margin-bottom: 20px;
        }
        #item_left{
            float: left;
        }
        #Acomment{
            font-size: 18px;
            margin-left: 20px;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <p>
            <div id="left">
                作者：{{ article.user.username }} &nbsp;&nbsp;&nbsp;&nbsp;
                发布时间：{{ article.pdatetime }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
            <div id="right">
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span><span>{{ article.save_num }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><span
                    tag="0">{{ article.love_num }}</span>
            </div>
            </p>
            <br>
            <br>
            <div>
                {{ article.content | cdecode | safe }}
            </div>
        </div>
        <hr>
        <div id="comment">
            <h3 style="text-align: center;">文章评论</h3>
            <div>
                <form action="{{ url_for('article.add_comment') }}" method="post">
                    <input type="hidden" value="{{ article.id }}" name="aid">
                    <p>
                        <textarea name="comment" id="" cols="100" rows="2"></textarea>
                    </p>
                    <input type="submit" class="btn-primary" value="评论">
                </form>
            </div>
            <div id="comment_item">
                {% if comments.items %}
                    {% for comment in comments.items %}
                        <div id="item">
                            <div id="item_left">
                                <img src="{% if comment.user.icon %}{{ url_for('static', filename=comment.user.icon ) }}
                                  {% else %}{{ url_for('static', filename='img/touxiang.png') }}{% endif %}"
                                     alt="" width="50" height="50" class="img-circle">
                            </div>
                            <div id="item_right">
                                <p style="margin-left: 10px; margin-top: 10px;">
                                    <span style="margin-left: 10px">{{ comment.user.username }}</span>
                                    <span style="margin-left: 10px">{{ comment.cdatetime }}</span>
                                </p>
                                <div id="Acomment">{{ comment.comment}}</div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div id="item">没有评论</div>
                {% endif %}
            </div>
        </div>
        <nav aria-label="Page navigation" class="col-md-offset-4">
            <ul class="pagination">
                <li {% if not comments.has_prev %}class="disabled" {% endif %} >
                    <a href="{{ url_for('article.article_detail') }}?page={{ comments.page - 1 }}&aid={{ article.id }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% for page_num in range(1,comments.pages + 1) %}
                    <li {% if comments.page==page_num %}class="active"{% endif %} >
                        <a href="{{ url_for('article.article_detail') }}?page={{ page_num }}&aid={{ article.id }}">{{ page_num }}</a>
                    </li>
                {% endfor %}
                <li {% if not comments.has_next %}class="disabled" {% endif %} >
                    <a href="{{url_for('article.article_detail')}}?page={{ comments.page + 1 }}&aid={{ article.id }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            $('.glyphicon-heart').click(function () {

            })
            $('.glyphicon-thumbs-up').click(function () {
                let $this = $(this)
                let tag = $this.next('span').attr('tag')
                $.get('{{ url_for('article.article_love') }}', {aid:{{article.id}}, tag: tag}, function (data) {
                    $this.next('span').text(data.love)

                })
                if (tag == 1) {
                    $this.css({'color': 'black'})
                    $this.next('span').attr('tag', "0")
                } else {
                    $this.css({'color': 'red'})
                    $this.next('span').attr('tag', "1")
                }

            })
        })
    </script>
{% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}This is an example page{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        body{
            background-image: url("{{ url_for('static', filename = 'img/bgc.jpg') }}");
            background-attachment: fixed;
			background-size: 100%;
        }
        .navbar{

            margin-top:10px;
        }
        #myfooter {
            border-top: 1px solid black;
            font-size: 14px;
            text-align: center;
            color: dimgray;
        }
    </style>
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <a class="navbar-brand" href="#">三个鸡毛的博客</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/user/">首页 <span class="sr-only">(current)</span></a></li>
                    <li><a href="/user/showabout">关于作者</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">文章分类<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">运动杂文</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">慢生活</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">生活</a></li>
                        </ul>
                    </li>
                    <li><a href="#">我的文章</a></li>
                    <li><a href="/user/show_photo">我的相册</a></li>
                    <li><a href="/user/board">留言板</a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user %}
                        <img src="{% if user.icon %}{{ url_for('static', filename=user.icon) }}{% else %}{{ url_for('static', filename = 'img/touxiang.png') }}{% endif %}"
                             alt="" class="img-circle" width="40" height="40" style="margin: 4px">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">欢迎，{{ user.username }}<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{url_for('user.user_center')}}">用户中心</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{url_for('user.logout')}}">退出</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="/user/login">登录</a></li>
                        <li><a href="/user/register">注册</a></li>
                    {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}

{% block content %}
    {% block newcontent %}
        <h1>Hello, Bootstrap</h1>
    {% endblock %}
    {% block footer %}
        <p id="myfooter">
            Designed and built with all the love in the world by @mdo and @fat.
        </p>
    {% endblock %}
{% endblock %}

templates/goods/findgoods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购买清单</title>
</head>
<body>
<h2>用户：{{ user.username }}</h2>
<h2>购买商品如下：</h2>
{% for good in user.goods %}
    <p>{{ good.gname }}___{{ good.price }}</p>
{% endfor %}

</body>
</html>

templates/goods/finduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购买用户名单</title>
</head>
<body>
<h1>商品： {{ goods.gname }}</h1>
<br>
<h2>购买该商品的用户为：</h2>
{% for user in goods.users %}
<p>
    <a href="{{ url_for('goods.find_goods') }}?uid={{ user.id }}">{{ user.username }}</a>
</p>
{% endfor %}

</body>
</html>

templates/goods/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物界面</title>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
<form action="">
    <p>
        <select name="uid">
            <option value="0">选择用户</option>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}

        </select>
    </p>
    <p>
        <table border="1" cellspacing="0" width="50%">
            <tr>
                <th>序号</th>
                <th>商品名</th>
                <th>价格</th>
                <th>操作</th>
            </tr>
            {% for good in goods %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td><a href="{{ url_for('goods.find_users') }}?gid={{ good.id }}">{{ good.gname }}</a></td>
                    <td>{{ good.price }}</td>
                    <td><input type="button" class="btnbuy" value="购买" tag="{{ good.id }}"></td>
                </tr>
            {% endfor %}

        </table>
    </p>
</form>
<script>
    $('.btnbuy').click(function (){
        let good_id = $(this).attr('tag');
        let user_id = $('select[name="uid"]').val();
        location.href = '/buy?uid='+user_id+'&gid='+good_id;
    })
</script>
</body>
</html>

templates/user/aboutme.html
{% extends 'base.html' %}

{% block title %}
关于作者
{% endblock %}

{% block styles %}
{{ super() }}
    <style>
        #container{
            width: 1000px;
            margin: 0 auto;
        }
        #container p{
            width: 80%;
            background-color: rgba(255, 255, 255, 0.5);
            font-size: 18px;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
    <p>
        {% if user.aboutme %}
            {{ user.aboutme[0].content | cdecode | safe }}
        {% else %}
            没有设置信息，去用户中心设置
        {% endif %}
    </p>
    </div>
{% endblock %}

templates/user/board.html
{% extends 'base.html' %}

{% block title %}
    留言板
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1000px;
            margin: 0 auto;
            background-color: rgba(30, 150, 196, 0.5);
        }

        #left {
            float: left;
        }

        #right {
            float: right;
        }
        #item{
            background-color: rgba(255, 255, 255, 0.5);
            margin-bottom: 20px;
        }
        #item_left{
            float: left;
        }
        #Acomment{
            font-size: 18px;
            margin-left: 20px;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">


        <div id="comment">
            <p>用户留言</p>
            <div>
                <form action="{{ url_for('user.show_board') }}" method="post">
                    <input type="hidden" value="" name="aid">
                    <p>
                        <textarea name="board" id="" cols="100" rows="10"></textarea>
                    </p>
                    <input type="submit" class="btn-primary" value="留言">
                </form>
            </div>
            <div id="comment_item">
                {% if boards %}
                    {% for board in boards.items %}
                        <div id="item">
                            <div id="item_left">
                                <img src="{% if board.user.icon %}{{ url_for('static', filename=board.user.icon) }}
                                            {% else %}{{ url_for('static', filename='img/touxiang.png') }}{% endif %}"
                                     alt="" width="50" height="50" class="img-circle">
                            </div>
                            <div id="item_right">
                                <p style="margin-left: 10px; margin-top: 10px;">
                                    <span style="margin-left: 10px">{% if not board.user_id %}匿名用户
                                        {% else %}{{board.user.username}}{% endif %}</span>
                                    <span style="margin-left: 10px">{{ board.mdatetime}}</span>
                                </p>
                                <div id="Acomment">{{ board.content }}</div>
                            </div>
                        </div>
                    {% endfor %}

                {% else %}
                    还没有留言，快来吧~~~~~~~
                {% endif %}
            </div>
        </div>
        <nav aria-label="Page navigation" class="col-md-offset-4">
            <ul class="pagination">
                <li {% if not boards.has_prev %}class="disabled" {% endif %} >
                    <a href="{{ url_for('user.show_board') }}?page={{ boards.page - 1 }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% for page_num in range(1,boards.pages + 1) %}
                    <li {% if boards.page==page_num %}class="active"{% endif %} >
                        <a href="{{ url_for('user.show_board') }}?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}
                <li {% if not boards.has_next %}class="disabled" {% endif %} >
                    <a href="{{url_for('user.show_board')}}?page={{ boards.page + 1 }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {

        })
    </script>
{% endblock %}

templates/user/center.html
{% extends 'base.html' %}

{% block title %}
    用户中心
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
            margin-bottom: 50px;
        }

        #container div {
            float: left;
        }

        #left {
            width: 25%;
        }

        #left p {
            width: 85%;
            margin: 40px auto;
            border: 1px solid lightskyblue;
            border-radius: 5px;
            text-align: center;
            font-size: 18px;
            color: white;
            padding: 7px;
            cursor: default;
            background-color: rgba(30, 150, 196, 0.94);
            box-shadow: 5px 5px 5px deepskyblue;
        }

        #left p:hover {
            background-color: skyblue;
            box-shadow: 5px 5px 5px deepskyblue;
        }

        #right {
            width: 74%;
            height: 500px;
            border: 5px solid deepskyblue;
            background-color: rgba(30, 150, 196, 0.5);
            margin-left: 5px;
        }

        #right1 {
            width: 90%;
            margin: 0 auto;
            text-align: center;
            padding-left: 120px;
            padding-top: 50px;
        }

        .right_img {
            margin-bottom: 20px;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
            <p>相册管理</p>
            <p>我的设置</p>
            <p>管理留言</p>
        </div>
        <div id="right">
            <div id="right1" class="right1">
                <form action="{{ url_for('user.user_change') }}" method="post" enctype="multipart/form-data"
                      class="form-horizontal">
                    <h1>用户信息修改</h1>
                    <p class=" form-group">
                        <input type="text" class="form-control" id="InputName" name="username"
                               value="{{ user.username }}">
                    </p>
                    <p class="form-group">
                        <input type="text" class="form-control" id="InputPhone" name="phone" value="{{ user.phone }}">
                        <span></span>
                    </p>
                    <p class="form-group">
                        <input type="email" class="form-control" id="InputEmail" name="email" value="{{ user.email }}">
                    </p>
                    <p class="form-group">
                        <input type="file" id="InputFile" name="icon">
                    </p>
                    <p>
                        <img src="




                                {% if user.icon %}{{ url_for('static', filename=user.icon) }}{% else %}{{ url_for('static', filename = 'img/touxiang.png') }}{% endif %}"
                             alt="" height="100" width="90">
                    </p>

                    <button type="submit" class="btn btn-info">确认修改</button>
                </form>
            </div>
            <div id="right1" class="right1">
                <form action="{{ url_for('article.article_publish') }}" method="post">
                    <p><input type="text" class="form-control" name="title" placeholder="请输入文章标题"></p>
                    <p>
                        <select name="type" id="" class="form-control">
                            <option value="0">请输入文章类别</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.type_name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p>
                        <textarea name="content" class="mytextarea" id="" cols="30" rows="10">

                        </textarea>
                    </p>
                    <button type="submit" class="btn btn-info">确认发布</button>
                </form>
            </div>
            <div id="right1" class="right1">
                <form action="{{ url_for('user.upload_photo') }}" method="post" enctype="multipart/form-data"
                      class="form-inline">
                    <input type="file" name="photo" class="form-control">
                    <input type="submit" class="btn-info" value="上传照片">
                </form>
                <h3>我的相册</h3>
                <div>
                    {% for photo in photos %}
                        <div class="col-xs-8 col-sm-4 right_img">
                            <img src="http://qxvd4jojt.hn-bkt.clouddn.com/{{ photo.photo_name }}" alt=""
                                 class="img-rounded image1" height="100" width="100">
                            <input type="button" class="btn btn-primary photo-del" value="删除" tag="{{ photo.id }}">
                        </div>

                    {% endfor %}

                </div>
            </div>
            <div id="right1" class="right1">
                <form action="{{ url_for('user.about_me') }}" method="post" enctype="multipart/form-data">
                    <p>
                        <textarea name="about" class="mytextarea"></textarea>
                    </p>
                    <p>
                        <input type="submit" value="更改信息" class="btn-primary">
                    </p>
                </form>
            </div>
            <div id="right1" class="right1" style="padding-top: 30px;">
                {% if user.messages %}
                    <table class="table table-hover">
                        <tr>
                            <th>序号</th>
                            <th>留言</th>
                            <th>时间</th>
                            <th>操作</th>
                        </tr>
                    {% for message in user.messages %}
                        <tr {% if loop.index%2 == 1 %}class="warning" {% endif %}>
                            <td>{{ loop.index }}</td>
                            <td>{{ message.content }}</td>
                            <td>{{ message.mdatetime }}</td>
                            <td><a href="{{ url_for('user.board_delete') }}?bid={{ message.id }}">删除留言</a></td>
                        </tr>
                    {% endfor %}

                    </table>
                {% else %}
                    没有留言，快去留言板发言~~~~~~
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/center.js') }}"></script>
    <script>
        $(function () {
            $('.right1').hide();
            $('.right1').first().show();
            $("#left p").each(function (i) {
                $(this).click(function () {
                    $(".right1").hide()
                    $(".right1").eq(i).show()
                })
            });

            tinymce.init({
                selector: '.mytextarea',
                height: 300,
                inline: false,
                toolbar: true,
                menubar: true,
                plugins: 'advlist autolink link image lists preview',
                quickbars_selection_toolbar: 'bold italic | link h2 h3 blockquote'

            });
        })
    </script>
{% endblock %}